version: "3.9"
services:
  pjobq:
    image: pjobq
    environment:
      - LOG_LEVEL
      - PGDB
      - PGHOST
      - PGUSER
      - PGPASSWORD

  db:
    image: postgres:13.1
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDB}
    volumes:
    - db_data:/var/lib/postgresql/data


volumes:
  db_data:
